apiVersion: v1
kind: ConfigMap
metadata:
  name: gameon-env
  namespace: default
data:
  service_map: https://map:9443/map/v1/sites
  service_room: ws://room:9080/rooms
  service_simpleroom: ws://simpleroom:9090/rooms
  GITHUB_APP_ID: ''
  GITHUB_APP_SECRET: ''
  TWITTER_CONSUMER_KEY: ''
  TWITTER_CONSUMER_SECRET: ''
  MAP_SERVICE_URL: http://127.0.0.1:6379/map/map/v1/sites
  PLAYER_SERVICE_URL: http://127.0.0.1:6379/players/players/v1/accounts
  COUCHDB_SERVICE_URL: http://couchdb:5984
  KAFKA_SERVICE_URL: kafka:9092
  FRONT_END_PLAYER_URL: https://173.193.107.30:30443/players/v1/accounts
  FRONT_END_SUCCESS_CALLBACK: https://173.193.107.30:30443/#/login/callback
  FRONT_END_FAIL_CALLBACK: https://173.193.107.30:30443/#/game
  FRONT_END_AUTH_URL: https://173.193.107.30:30443/auth
  GAMEON_MODE: development
  TARGET_PLATFORM: local
  SYSTEM_ID: game-on.org
  LICENSE: accept
  PROXY_DOCKER_HOST: '173.193.107.30'
  ADMIN_PASSWORD: admin
  WLP_SKIP_MAXPERMSIZE: 'true'
  WLP_OUTPUT_DIR: /opt/ibm/wlp/usr/servers/
  LOG_DIR: /opt/ibm/wlp/usr/servers/defaultServer/logs
  MAP_KEY: fish
  COUCHDB_USER: mapUser
  COUCHDB_PASSWORD: myCouchDBSecret
  A8_REGISTRY_URL: http://registry:8080
  A8_CONTROLLER_URL: http://controller:8080
  A8_CONTROLLER_POLL: 5s
  A8_CONTROLLER_POLL: 5s
